"""Created Chef model

Revision ID: 2d117c600a55
Revises: 5322e94c5fb0
Create Date: 2025-11-13 19:50:35.247431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d117c600a55'
down_revision: Union[str, Sequence[str], None] = '5322e94c5fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipe', sa.Column('chef_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'chef', ['chef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'chef_id')
    op.drop_table('chef')
    # ### end Alembic commands ###
