# Generated by Django 5.0.4 on 2026-02-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('employees_count', models.PositiveIntegerField(default=1, verbose_name='Employees Count')),
                ('location', models.CharField(choices=[('SF', 'Sofia'), ('PD', 'Plovdiv'), ('V', 'Varna'), ('BS', 'Burgas')], max_length=20)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
