# Generated by Django 5.0.4 on 2026-03-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_laptop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='operating_system',
            new_name='operation_system',
        ),
    ]
